<?php

/**
 * PluginaPersonToACategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaPersonToACategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPersonToACategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPersonToACategory');
    }
    
    public function mergeCategory($old_id, $new_id)
    {
      Doctrine::getTable('aCategory')->mergeCategory($old_id, $new_id, 'aPersonToACategory', 'category_id', true, 'person_id');
    }
}