<?php

/**
 * Person
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pennldi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginaPerson extends BaseaPerson
{
  public function getName()
  {
    if ($this->getMiddleName())
    {
      return $this->getFirstName() . ' ' . $this->getMiddleName() . ' ' . $this->getLastName();
    }

    return $this->getFirstName() . ' ' . $this->getLastName();
  }
  
  public function getNameAndSuffix()
  {
    $name = $this->getName();
    
    if ($this->getSuffix()) $name .= ', ' . $this->getSuffix();
    
    return $name;
  }
  
}
